baseURL = 'https://xxy-maimai.github.io/'
locale = 'zh-cn'
title = 'XxyBlog'
theme = 'PaperMod'

[params.homeInfoParams]
 Title = "屑小鱼的个人博客"
 Content = "欢迎回来"

 [params]
        math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]